MuOnlineWebMVC/Controllers/LoginController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MuOnlineWebMVC.Models;
using MuOnlineWebMVC.Models.AccountViewModels;
using Microsoft.EntityFrameworkCore;
using AutoMapper;
using MuOnlineWebMVC.Models.ViewModels.AccountViewModels;
using MuOnlineWebMVC.Extensions.Alerts;
using MuOnlineWebMVC.Models.ViewModels;
using System.Diagnostics;

namespace MuOnlineWebMVC.Controllers
{
    public class LoginController : Controller
    {
        ApplicationDbContext _dbContext { get; set; }
        public static string erro = "false";
        public static int countErro = 0;
        public LoginController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public IActionResult _signUp()
        {
            if(countErro == 2) { countErro = 0; erro = "false"; }
            ViewData["Erro"] = erro;
            countErro++;
            return PartialView();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> _signUp(LoginViewModel model)
        {
            erro = "false";
            var logar = await _dbContext.MembInfo.Where(p => p.MembId.Equals(model.UserName)).Where(p => p.MembPwd.Equals(model.Password)).FirstOrDefaultAsync();

            if (logar == null)
            {
                countErro = 1;
                erro = "Login ou senha inválidos.";
                return RedirectToAction("Index", "Home");
            }           
            
            if (ModelState.IsValid)
            {
                try
                {
                    erro = "false";
                    var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Name, ClaimTypes.Role);
                    identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, model.UserName));
                    identity.AddClaim(new Claim(ClaimTypes.Name, model.UserName));
                    var principal = new ClaimsPrincipal(identity);
                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                    return RedirectToAction("Index","Painel");
                }
                
                catch(Exception e)
                {
                    ModelState.AddModelError("","Erro ocorrido : \n" + e.Message);
                }
            }
            return View();

        }

        public IActionResult Register()
        {
            var username = User.Identity.Name;

            if (username != null)
                return RedirectToAction(nameof(Error), new {Message = "Você precisa estar deslogado para executar essa operação."} );

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterMembInfoViewModel model)
        {

            var membInfo = Mapper.Map<MembInfo>(model);

            membInfo.BlocCode = "0";
            membInfo.Ctl1Code = "0";
            if (ModelState.IsValid)
            {
                try
                {
                    _dbContext.Add(membInfo);
                    await _dbContext.SaveChangesAsync();
                    ViewBag.Sucess = "Cadastro realizado com sucesso.";
                    return RedirectToAction(nameof(HomeController.Index)).WithSuccess("Seja bem-vindo!","Cadastro realizado com sucesso!");
                }

                catch (Exception e)
                {
                    ModelState.AddModelError("", "Erro ocorrido: \n" + e.Message);
                }
            }
            return View(model).WithDanger("Erro ocorrido!","Preencha novamente o formulário de maneira correta!");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

        public IActionResult Error(string message)
        {
            var viewModel = new ErrorViewModel
            {
                Message = message,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };

            return View(viewModel);
        }
    }
}

MuOnlineWebMVC/Controllers/RankingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MuOnlineWebMVC.Models;
using MuOnlineWebMVC.Services;
using MuOnlineWebMVC.Utils;

namespace MuOnlineWebMVC.Controllers
{
    public class RankingController : Controller
    {
        private readonly ApplicationDbContext _dbContext;

        public RankingController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index(string filtroAtual, string filtro, int? pagina)
        {     
            if (filtro != null)
            {
                pagina = 1;
            }
            else
            {
                filtro = filtroAtual;
            }

            ViewData["filtroAtual"] = filtro;

            var character = from charact in _dbContext.Character select charact;

            //if (!String.IsNullOrEmpty(filtro))
            //{
            //    character = character.Where(x => x.Name.Contains(filtro));
            //}

            switch (filtroAtual)
            {
                case "Resets":
                    character = character.OrderByDescending(est => est.Resets);
                    break;
                case "ResetSemanal":
                    character = character.OrderByDescending(x => x.ResetsWeek);
                    break;
                case "MasterReset":
                    character = character.OrderByDescending(x => x.MrTotal);
                    break;
                case "MasterReset Semanal":
                    character = character.OrderByDescending(x => x.MrSemanal);
                    break;
                case "PlayerKiller":
                    character = character.OrderByDescending(x => x.PkHeroTotal);
                    break;
                case "PlayerKiller Semanal":
                    character = character.OrderByDescending(x => x.ResetsWeek);
                    break;

                default:
                    character = character.OrderByDescending(est => est.Resets);
                    break;
            }

            int pageSize = 2;
            return View(await PaginatedList<Character>.CreateAsync(character.AsNoTracking(), pagina ?? 1,pageSize));
        }

    }
}

MuOnlineWebMVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MuOnlineWebMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MuOnlineWebMVC</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Login" asp-action="Register">Register</a></li>
                    <li><a asp-area="" asp-controller="Ranking" asp-action="Index">Rankings</a></li>


                </ul>
                <div id="Login"></div>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @await Html.PartialAsync("_StatusMessages")


        <div class="row">
            @RenderBody()
        </div>
        <hr />
        <div align="center" class="row">
            <footer>
                <p>&copy; @DateTime.Now.Year - MuOnlineWebMVC</p>
            </footer>
        </div>



    </div>

        
    
    <script type="text/javascript"
            src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script type="text/javascript">
        function carregaLogin() {

            $.ajax(
                {
                    type: 'GET',
                    url: '/Login/_signUp',
                    dataType: 'html',
                    cache: false,
                    async: true,
                    success: function (data) {
                        $('#Login').html(data);
                    }
                });
        } carregaLogin()
    </script>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

MuOnlineWebMVC/Views/Shared/_RankingMasterResets.cshtml
@model Character

<form asp-controller="Home" asp-action="RankingMasterResets">

    <h4 align="center">Top Master Resets</h4>
    <ul class="list-group">
        
            <li class="list-group-Model-success" align="center">  @Model.Name</li>
            <li class="list-group-Model" align="center"><img src="~/Characters/@Model.Image" class="img-rounded" height="200" width="200" /></li>
            <li class="list-group-Model" align="center"><small><strong>@Model.MrTotal</strong> Resets</small></li>
        
    </ul>
</form>

MuOnlineWebMVC/Views/Shared/_StatusMessages.cshtml
@{
    var type = (string)TempData["_alert.type"];
    var title = (string)TempData["_alert.title"];
    var body = (string)TempData["_alert.body"];
}
@if (!string.IsNullOrEmpty(type))
{
    <br />
    <br />

    <div class="alert alert-@type alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <strong>@title</strong><br /> @body
    </div>
}

MuOnlineWebMVC/Views/Shared/_signUp.cshtml
@model MuOnlineWebMVC.Models.ViewModels.AccountViewModels.LoginViewModel
@{

    var a = ViewData["Erro"] as string;
    if (a == null || a == "") { a = "false"; }

}

@if (@User.Identity.IsAuthenticated)
{
    <form asp-area="" asp-controller="Login" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a asp-area="" asp-controller="Painel" asp-action="Index" title="Manage">Hello @User.Identity.Name</a>
            </li>
            <li>
                <button type="submit" class="btn btn-link navbar-btn navbar-link" value="Logout">Log out</button>
            </li>
        </ul>
    </form>
}
else
{

    <div class="container">
        <ul class="nav navbar-nav navbar-right">
            <li><button type="button" id="btnLogin" class="btn btn-link navbar-btn navbar-link" data-toggle="modal" data-backdrop="false" data-target="#loginModal">Login</button></li>
        </ul>
        <!-- Modal -->
        <div class="modal fade" id="loginModal" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 style="color:red;"><span class="glyphicon glyphicon-lock"></span> Login</h4>
                    </div>

                    <div class="modal-body">
                        <form role="form" asp-area="" asp-controller="Login" asp-action="_signUp" method="post">
                            @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@

                            <div class="form-group">
                                <label asp-for="UserName"><span class="glyphicon glyphicon-user"></span> Login</label>
                                <input asp-for="UserName" maxlength="10" class="form-control" placeholder="Informe o nome do usuario" />
                            </div>
                            <div class="form-group">
                                <label asp-for="Password"><span class="glyphicon glyphicon-eye-open"></span> Senha</label>
                                <input type="password"maxlength="10" asp-for="Password" class="form-control" placeholder="Informe a senha" />
                            </div>
                            <div class="form-group">
                                @if (a != "false")
                                { 
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <span class="text-danger"> @a</span>
                                </div>
                                }
                            </div>
                            <button type="submit" class="btn btn-default btn-success btn-block">
                                <span class="glyphicon glyphicon-ok"></span> Login
                            </button>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-default btn-default pull-left" data-dismiss="modal">
                            <span class="glyphicon glyphicon-remove"></span> Cancelar
                        </button>
                        <p>N&atilde;o &eacute; um membro? <a href="#">Assine</a></p>
                        <p>Esqueceu a <a href="#">Senha?</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
@if (a != "false")
{
    <script type="text/javascript">
        $("#btnLogin").click();
    </script>
}